### ISSUE TITLE
Coastline not showing

### ISSUE THREAD

**Issue by prise6** [ecmwf/magics-python#10]
Hi,

I try to understand why in my plots i can't see any coastline.
For example this code :

```
import Magics.macro as magics
magics.plot(magics.mcoast())
```

give me this plot:
![github_issue_mcoast](https://user-images.githubusercontent.com/6558161/55540641-acd89f80-56c3-11e9-8dd7-212873f4589e.png)

OS: ubuntu 18.04
Magics installation: 	conda install -y -c conda-forge Magics=4.0.0

i would like to know if you have some test i can run to help me find why i can't draw coasts ?

Thanks

**Comment by StephanSiemen** [comment]
Hi @prise6 ,
Did you get any error/warning messages? This seems to happen the the shapefiles wwhihc contain the coastlines can not be found at runtime. But there should be messages on that?!
Can not see this on any of my tests environments, but just downloading an Ubuntu 18.04 ...
Get back to you
Stephan

**Comment by StephanSiemen** [comment]
Hi @prise6 ,
unfortunately, I can not reproduce your problem. Under Ubuntu 18.04 with mini conda I get the coastlines. Could you please try the python code
   magics.info()
after your lines and tell us what you get?
Thanks

**Comment by prise6** [comment]
Hi @StephanSiemen,
Thank you for your answer.
I do not have any warning or errors when using magics. This is the reason why i'm a bit lost.
Is there a debug mode i can turn on ?

Here is the executed code you ask:
```
magics.info()

Checking Magics: Magics 4.0.0 (64 bit)
Configuration files found in /opt/conda
```
I use docker, here's my Dockerfile:

```
FROM jupyter/tensorflow-notebook:7f1482f5a136

USER root

RUN apt-get update && \
    apt-get install -y \
    libmagplus3v5 \ 
    libproj-dev \
    proj-data \
    proj-bin \
    gdal-bin \
    libgeos-dev \
    libssl1.0.0 \
    libssl-dev

RUN conda install -y -c conda-forge python-eccodes cartopy Magics=4.0.0

USER $NB_UID
```

Can you tell me where i shoud find my _shapefiles wwhihc_ in my system ? 

Thank you again.

**Comment by StephanSiemen** [comment]
Hi @prise6 ,
I can currently not try your setup, but I noticed that you install Magics through apt-get and Conda. You do not need the apt-get one if you have Conda since Magics 4.0. Perhaps there is a mismatch if both versions are installed? Please try remove the installation of Magics through apt-get ("libmagplus3v5") and see if this helps.
Cheers

**Comment by prise6** [comment]
@StephanSiemen ,
I removed `libmagplus3v5` and build my image, unfortunately it doesn't work :/ 
Could it be a permission problem ?

**Comment by oldtree2008** [comment]
I have the same problem.Magics-ERROR: Can not open Shapefile /home/XXXX/anaconda3Magics

**Comment by oldtree2008** [comment]
I have solved the problem. just set Environment variant MAGPLUS_HOME.

**Comment by dtip** [comment]
@oldtree2008 if you activate your conda environment ```MAGPLUS_HOME``` should be automatically set.
